name: Build project with Maven
on:
  pull_request:
    branches: [ main ]
  push:
    branches-ignore: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      # Build for three operating systems, currently JVMs 11, 17 and latest four Camunda versions (last two years)
      # We run Legacy support test on Ubuntu, JDK 1.8 until 7.10 (Release end of 2018).
      matrix:
        jdk:
          - '8'
          - '11'
          - '17'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@e9512a931da86017e9d4d564a24616d8444d2193 # pin@v2
    - name: Java setup
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jdk }}
    - name: Cache
      uses: actions/cache@99d99cd262b87f5f8671407a1e5c1ddfa36ad5ba # pin@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Run Maven
      run: mvn -B clean install com.mycila:license-maven-plugin:check
