name: CI
on: [ pull_request ]
jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ["8","11","17"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java-version }}
        cache: 'maven'
    - name: Build
      run: mvn test -P!autoFormat -B      
      
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: mvn verify -PcheckFormat -B
